TobJod/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TobJod.Models;
using TobJod.Repositories;
using TobJod.Utils;

namespace TobJod.Web.Controllers {
    public class AboutController : BaseController {
        // GET: About
        public ActionResult Index() {
            ConfigPageRepository repo = new ConfigPageRepository();
            var model = repo.GetConfigPage(TobJod.Models.ConfigPageName.AboutUs);
            PageMeta.FromConfigPage(model, Language);
            return View(Language.ToString() + "/Index", model);
        }


        // POST: About/Preview
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Preview(String body) {
            if (NullUtils.cvBoolean(System.Configuration.ConfigurationManager.AppSettings["Backend_Preview"])) {
                ConfigPageRepository repo = new ConfigPageRepository();
                ConfigPage model = repo.GetConfigPage_Admin(ConfigPageName.AboutUs);
                model.BodyTH = ReplaceTextEditorPathDisplay(body);
                model.BodyEN = ReplaceTextEditorPathDisplay(body);
                return View(Language.ToString() + "/Index", model);
            } else {
                return Redirect("Index");
            }
        }

    }
}

TobJod/Controllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TobJod.Repositories;

namespace TobJod.Web.Controllers {
    public class FAQController : BaseController {
        // GET: FAQ
        public ActionResult Index() {
            FaqRepository repo = new FaqRepository();
            var model = repo.ListFaq_Active(Language);
            ViewBag.Pin = repo.ListFaqPin_Active(Language, 5);
            return View(Language.ToString() + "/Index", model);
        }
    }
}

TobJod/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TobJod.Repositories;
using TobJod.Utils;
using TobJod.Web.Models;
using TobJod.Models;

namespace TobJod.Web.Controllers {
    public class NewsController : BaseController {
        // GET: News
        public ActionResult Index() {
            NewsSubCategoryRepository catRepo = new NewsSubCategoryRepository();
            var sub = catRepo.ListNewsSubCategory_SelectList_Active(Language);
            NewsListViewModel model = new NewsListViewModel();
            model.SubCategoryList = new SelectList(sub, "Id", "Title" + Language.ToString());
            model.UrlUpload = HttpUtils.GetPathRelative(System.Configuration.ConfigurationManager.AppSettings["Path_News"]);

            ViewBag.SubCategoryJson = sub.GroupBy((x) => x.NewsCategory).Select(g => new {
                GroupId = g.Key,
                Items = g.Select(i => new {
                    Text = (Language == TobJod.Models.Language.TH ? i.TitleTH : i.TitleEN),
                    Value = i.Id
                }).ToList()
            });

            return View(Language.ToString() + "/Index", model);
        }

        public ActionResult List() {
            int category = NullUtils.cvInt(Request.Params["c"]);
            int subCategory = NullUtils.cvInt(Request.Params["s"]);
            int pageNo = GetPageNo();

            NewsRepository repo = new NewsRepository();
            var model = repo.ListNews_Active(Language, pageNo, 6, category, subCategory);
            

            var data = new { page = pageNo, data = model.Select((x) => new NewsListItemViewModel() { Title = (Language == Language.TH ? x.TitleTH : x.TitleEN), SubCategory = x.NewsSubCategory, Brief = (Language == Language.TH ? x.BriefTH.ReplacePath() : x.BriefEN.ReplacePath()), Image = (Language == Language.TH ? x.ImageTH : x.ImageEN), ImageAlt = (Language == Language.TH ? x.ImageAltTH : x.ImageAltEN), ImageTitle = (Language == Language.TH ? x.ImageTitleTH : x.ImageTitleEN), Url = "News/" + x.UrlPrefix + "/" + (Language == Language.TH ? x.UrlTH : x.UrlEN), Date = x.CreateDate.ToString("dd MMMM yyyy", cultureInfo) }).ToList() };

            return Json(data, JsonRequestBehavior.AllowGet);

            //return PartialView(Language.ToString() + "/List", model);
        }

        // GET: News/slug
        public ActionResult Detail(int year = 0, string slug = "") {
            if (year == 0 && string.IsNullOrEmpty(slug)) return RedirectToAction("Index");
            NewsRepository repo = new NewsRepository();
            var item = repo.GetNews_Active(year.ToString(), slug, Language, 3);
            NewsListViewModel model = new NewsListViewModel();
            if (item.Item1 == null) return RedirectToAction("Index");
            model.News = item.Item1;
            model.NewsList = item.Item2;
            model.UrlUpload = HttpUtils.GetPathRelative(System.Configuration.ConfigurationManager.AppSettings["Path_News"]);


            if (Language == Language.TH) {
                PageMeta.Title = model.News.MetaTitleTH;
                PageMeta.MetaDescription = model.News.MetaDescriptionTH;
                PageMeta.MetaKeyword = model.News.MetaKeywordTH;
                PageMeta.OGTitle = model.News.OGTitleTH;
                PageMeta.OGImage = (!string.IsNullOrEmpty(model.News.OGImageTH) ? HttpUtils.GetPathUrlAbsolute(System.Configuration.ConfigurationManager.AppSettings["Path_News"]) + model.News.OGImageTH : PageMeta.OGImage);
                PageMeta.OGDescription = model.News.OGDescriptionTH;
                ViewBag.UrlLang = "/../" + model.News.UrlPrefix + "/" + model.News.UrlEN;
            } else {
                PageMeta.Title = model.News.MetaTitleTH;
                PageMeta.MetaDescription = model.News.MetaDescriptionEN;
                PageMeta.MetaKeyword = model.News.MetaKeywordEN;
                PageMeta.OGTitle = model.News.OGTitleEN;
                PageMeta.OGImage = (!string.IsNullOrEmpty(model.News.OGImageEN) ? HttpUtils.GetPathUrlAbsolute(System.Configuration.ConfigurationManager.AppSettings["Path_News"]) + model.News.OGImageEN : PageMeta.OGImage);
                PageMeta.OGDescription = model.News.OGDescriptionEN;
                ViewBag.UrlLang = "/../" + model.News.UrlPrefix + "/" + model.News.UrlTH;
            }

            return View(Language.ToString() + "/Detail", model);
        }
    }
}

TobJod/Controllers/POIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TobJod.Models;
using TobJod.Repositories;
using TobJod.Utils;

namespace TobJod.Web.Controllers {
    public class POIController : BaseController {

        // GET: POI
        public ActionResult Index() {
            //ConfigPageRepository repo = new ConfigPageRepository();
            //var model = repo.GetConfigPage(TobJod.Models.ConfigPageName.POI);
            //PageMeta.FromConfigPage(model, Language);
            PoiRepository repo = new PoiRepository();
            ViewBag.POIGarage = repo.ListPoi_Active(Language, (int)PoiCategory.Garage);
            ViewBag.POIHospital = repo.ListPoi_Active(Language, (int)PoiCategory.Hospital);
            ViewBag.POIPolice = repo.ListPoi_Active(Language, (int)PoiCategory.Police);
            return View(Language.ToString() + "/Index");//, model);
        }


        // GET: POI/List
        public ActionResult List() {
            int category = NullUtils.cvInt(Request.Form["c"]);
            PoiRepository repo = new PoiRepository();
            var model = repo.ListPoi_Active(Language, category);
            return Json(model, JsonRequestBehavior.AllowGet);
        }

    }
}

TobJod/Controllers/SiteMapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TobJod.Web.Controllers {

    public class SiteMapController : BaseController {
        // GET: SiteMap
        public ActionResult Index() {
            return View(Language.ToString() + "/Index");
        }
    }
}

TobJod/Views/SiteMap/TH/Index.cshtml
@{ 
    Layout = "~/Views/Shared/TH/_Layout.cshtml";
    var pageMeta = (TobJod.Web.Models.PageMeta)ViewBag.PageMeta;
    pageMeta.Title = "แผนผังเว็บไซต์ | Tobjod โบรคเกอร์ ประกันภัย";
}
<main class="container sitemap">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>แผนผังเว็บไซต์</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <ul class="footer-menu-list-1 site-item">
                <li><b>เมนูตอบโจทย์</b></li>
                <li><a href="@Url.Action("Index", "Home")" target="_blank"><span>หน้าแรก</span></a></li>
                <li><a href="@Url.Action("Index", "News")" target="_blank"><span>ข่าวและกิจกรรม</span></a></li>
                <li><a href="#" target="_blank"><span>การบริการประกันภัย</span></a></li>
                <li class="submenu ">
                    <div class="inner">
                        <ul>
                            <li><a href="@Url.Action("Index", "FAQ")" target="_blank">คำถามที่พบบ่อย</a></li>
                            <li><a href="@Url.Action("Index", "ClaimProcess")" target="_blank">ขั้นตอนการเคลมประกันภัย</a></li>
                            <li><a href="@Url.Action("Index", "POI")" target="_blank">ค้นหาสถานที่บริการ</a></li>
                            <li><a href="@Url.Action("Index", "PaymentMethod")" target="_blank">ขั้นตอนการชำระเงิน</a></li>

                        </ul>
                    </div>
                </li>
                <li><a href="@Url.Action("Index", "Privilege")" target="_blank"><span>สิทธิพิเศษประกันภัย</span></a></li>
                <li><a href="@Url.Action("Index", "About")" target="_blank"><span>กี่ยวกับเรา</span></a></li>
                <li><a href="@Url.Action("Index", "Contact")" target="_blank"><span>ติดต่อเรา</span></a></li>
            </ul>
        </div>
        <div class="col-md-6">
            <ul class="footer-menu-list-2 site-item">
                <li><b>สินค้าประกันภัย</b></li>
                <li><a href="@Url.Action("Motor", "Product")" target="_blank"><span>ประกันภัยรถยนต์</span></a></li>
                <li><a href="@Url.Action("Compulsory", "Product")" target="_blank"><span>พ.ร.บ. รถยนต์</span></a></li>
                <li><a href="@Url.Action("TA", "Product")" target="_blank"><span>ประกันภัยการเดินทาง</span></a></li>
                <li><a href="@Url.Action("PA", "Product")" target="_blank"><span>ประกันภัยอุบัติเหตุส่วนบุคคล</span></a></li>
                <li><a href="@Url.Action("Health", "Product")" target="_blank"><span>ประกันสุขภาพ</span></a></li>
                <li><a href="@Url.Action("Home", "Product")" target="_blank"><span>ประกันภัยที่อยู่อาศัย</span></a></li>
            </ul>
        </div>
    </div>

</main>